export const TitleList = [
  { Type: "1", Title: "Salaried Person" },
  { Type: "2", Title: "Capital Gain" },
  { Type: "3", Title: "NRI" },
  { Type: "4", Title: "ITR" },
  {
    Type: "5",
    Title: "DSC Class III",
    Url: "http://localhost:88/v1/DSC/register",
  },
  {
    Type: "6",
    Title: "DSC Encrypted Individual",
    Url: "http://localhost:88/v1/DSCIndividual/register",
  },
  {
    Type: "7",
    Title: "DSC Encrypted Organisation",
    Url: "http://localhost:88/v1/DSCOrganisation/register",
  },
  {
    Type: "8",
    Title: "DSC DGFT",
    Url: "http://localhost:88/v1/DSCDGFT/register",
  },
  {
    Type: "9",
    Title: "DSC ICEGATE",
    Url: "http://localhost:88/v1/DSCICEGATE/register",
  },
  {
    Type: "10",
    Title: "DSC NRI",
    Url: "http://localhost:88/v1/DSCNRI/register",
  },
  { Type: "11", Title: "GST Registration" },
  { Type: "12", Title: "Rental Receipt" },
  { Type: "13", Title: "Business" },
  { Type: "14", Title: "TDS" },
  { Type: "15", Title: "LUT" },
  { Type: "16", Title: "Refunds" },
  { Type: "17", Title: "Amendments" },
  { Type: "18", Title: "GST Returns" },
  { Type: "19", Title: "Company" },
  { Type: "20", Title: "Partnership" },
  { Type: "21", Title: "LLP" },
  { Type: "22", Title: "MSME Registration" },
  { Type: "23", Title: "ROC Filing" },
  { Type: "24", Title: "IEC Registration" },
  { Type: "25", Title: "SFT" },
  { Type: "26", Title: "Seek Help" },
  { Type: "27", Title: "TDS Form26Q" },
  { Type: "28", Title: "TDS Form24Q" },
  { Type: "29", Title: "TDS Form26QB" },
  { Type: "30", Title: "TDS Form27Q" },
  { Type: "31", Title: "GST Returns 3B" },
  { Type: "32", Title: "GST Returns Lite" },
  { Type: "33", Title: "GST Returns Lite One" },
];
